[package]
name = "little_opengl"
version = "0.1.0"
authors = ["Thomas-QM <thomas@engineeringvirtue.net>"]
edition = "2018"

[dependencies]
little = {path = "../little"}
glutin = "0.21.0"
gl = "0.12.0"
mio = "0.6.18"